language: python
matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  allow_failures:
  - python: 3.4
  - python: 3.5
before_install:
- pip install -U pip setuptools wheel
install:
- travis_wait pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install .
- pip install --quiet coverage
- pip install --quiet coveralls
script:
- pytest -v --doctest-modules --ignore=setup.py --cov=. --cov-report=
after_success:
- coveralls
deploy:
  - provider: pypi
    distributions: bdist_wheel
    user: cjsewell
    password:
      secure: haaW5ws1WWKbJJJqxI6GvdnascvF90sQI6wyi2D/iMNr/UaVWFNqY675PQ/+piRtftQa+WR+4zWhJzksUSd8S56+e0rq+iX6vrz9yWRkt2p5e0OOSIg34/Ef0n7hxLkp5nMoPUbuHqftWPzaHnO89M/BZXUVhJdZA24BBRTvvBT5vLeUXTK5E5pso2L/NJMs7kUUvZZk9sg2StNdcskLhURkaPt6WpHCuJbZlr3h9NPHwb76rtThfHDjnooKX/wHNoyJmDpgNOG14Jx35XhFRkE54Z+rZZv9QqDVn+mFmiGozN4dhyaTulvfOW66b+EobHdwIUewLkmPq4BP7fPSCObiKz4k2EazceMvc+ksnyb86es5BBKPl+hzwP8iRNuWHRssHmg37X++C2m0GTcvFxMjPrO//4ow4vXzTn5rPOTjPv4mEJ3FaUMSyh7vPuJyKhnLHNAzJStkKsmgY5iWjjKYrplJeSCgMig4n++bX3juwwGFShGt2ANnEJIA8i4JBmW/+Pth5He/mLXgW5uFjcIUcW9ti1csOzB+FYYI/gN7Ta3tYjt4clm9okQBrmxxDFsSGOFvNZ3Nfcwf+OH48cPS2F+vFjkcsdBdOXu194te9ctjYb9uPuu5a5FaJlQKN7rkFONx5SXVqYd8aqYLHybU+s2Mtg1t6+/Bv4ycnP4=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
